### ISSUE TITLE
Route 53 RR Set Not Created

### ISSUE THREAD

**Issue by alexmbird** [coreos/alb-ingress-controller#215] opened 2017-09-18 14:21 UTC
As required to get past a panic after the AWS API call I'm running `quay.io/coreos/alb-ingress-controller:b30d8d28`.  In this version (I can't test others), no Route53 RR is getting created to match the value I've set in `spec.rules.host` within my Ingress.

Steps to replicate:
* Have a cluster with internal domain `sandbox-1.my.cluster.com`
* Setup aws-ingress-controller with appropriate IAM roles
* Specify an ingress with `host: echoserver.inst-1.sandbox-1.my.cluster.com`

Expected result:
* An `echoserver.inst-1` record within the `sandbox-1.my.cluster.com` hosted zone

Actual result:
* No RR visible in the appropriate hosted zone within the AWS UI
* Nothing about RRs in alb-ingress-controller's logs, even with `AWS_DEBUG=True`.  
* No crash or other complaints

**Comment by joshrosso** [comment] 2017-09-18 14:39
Hi @alexmbird 

Since 4d9c01c7817462476e20e6a241b5b48434bba751 we removed Route 53 integration completely from the controller.

We did this in favor of keeping the controller focused on just ALB concerns and allowing external projects, specifically https://github.com/kubernetes-incubator/external-dns, to provision DNS records.

Documenting how to make these 2 work together is part of https://github.com/coreos/alb-ingress-controller/pull/197 until then, you may wish to visit the external-dns project and checkout the docs.

**Comment by alexmbird** [comment] 2017-09-18 14:40
Gotcha, makes sense.  Thanks for the quick response.

**Comment by joshrosso** [comment] 2017-09-18 14:42
yw, apologies things are a bit in flux as we flesh out this controller for 1.0.

**Comment by alexmbird** [comment] 2017-09-18 16:13
Just FYI - I'm trying to make external-dns work with it and as of `0.4.2` my RRs aren't getting created. 

Their [FAQ](https://github.com/kubernetes-incubator/external-dns/blob/master/docs/faq.md#are-other-ingress-controllers-supported) does't list alb-ingress-controller officially supported and doesn't discover the `host:` I've set on my ingress.  So I'm guessing some integration work is needed at the external-dns end.

**Comment by joshrosso** [comment] 2017-09-18 18:42
@alexmbird rgr.

Some groups testing out this controller are using external-dns today, so I'm not quite sure what the root cause is.

I'm writing an end-to-end example now and it'll include external-dns example. I'll re-open this for now in case I run into the same thing.

**Comment by joshrosso** [comment] 2017-09-19 02:57
Hi @alexmbird 

After going through the docs at https://github.com/kubernetes-incubator/external-dns/blob/master/docs/tutorials/aws.md `external-dns` created my R53 records as expected. 2 things to note.

1. I was testing with the tag `1.0-alpha.0`, just cut today.

2. I adjusted the `--domain-filter` at https://github.com/kubernetes-incubator/external-dns/blob/master/docs/tutorials/aws.md#deploy-externaldns.

Please let me know if this helps.

**Comment by joshrosso** [comment] 2017-09-19 03:34
For more details on the step-by-step, feel free to checkout https://github.com/coreos/alb-ingress-controller/blob/continued_stabilization/docs/walkthrough.md

**Comment by joshrosso** [comment] 2017-09-20 04:52
Closing for now, happy to re-open if your results above don't match.

**Closed by joshrosso** 2017-09-20 04:52 UTC
Labels: kind/support
